package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;

import io.flutter.embedding.engine.FlutterEngine;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  private GeneratedPluginRegistrant() {}

  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    throw new UnsupportedOperationException("Not implemented");
  }
}
