name: WeatherMaster PR Build

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

  workflow_dispatch:
    inputs:
      pr_number:
        description: "PR number to build"
        required: true
        type: number

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || format('refs/pull/{0}/head', inputs.pr_number) }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "21.0.7"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build debug APK
        run: |
          ./gradlew \
            --no-daemon \
            --no-build-cache \
            clean assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: pr-debug-apk
          path: app/build/outputs/apk/debug/*.apk